use crate::color::ansi_3_bit::Ansi3Bit;
use crate::color::ansi_4_bit::Ansi4Bit;
use crate::color::ansi_8_bit::cube::Cube;
use crate::color::ansi_8_bit::grayscale::Grayscale;
use crate::color::ansi_8_bit::Ansi8Bit;

pub(super) const ANSI_3_BIT: [Ansi3Bit; 8] = [
    Ansi3Bit::Black,
    Ansi3Bit::Red,
    Ansi3Bit::Green,
    Ansi3Bit::Yellow,
    Ansi3Bit::Blue,
    Ansi3Bit::Magenta,
    Ansi3Bit::Cyan,
    Ansi3Bit::White,
];

pub(super) const ANSI_4_BIT: [Ansi4Bit; 16] = [
    Ansi4Bit::new_bright(Ansi3Bit::Black),
    Ansi4Bit::new_bright(Ansi3Bit::Red),
    Ansi4Bit::new_bright(Ansi3Bit::Green),
    Ansi4Bit::new_bright(Ansi3Bit::Yellow),
    Ansi4Bit::new_bright(Ansi3Bit::Blue),
    Ansi4Bit::new_bright(Ansi3Bit::Magenta),
    Ansi4Bit::new_bright(Ansi3Bit::Cyan),
    Ansi4Bit::new_bright(Ansi3Bit::White),
    Ansi4Bit::new_non_bright(Ansi3Bit::Black),
    Ansi4Bit::new_non_bright(Ansi3Bit::Red),
    Ansi4Bit::new_non_bright(Ansi3Bit::Green),
    Ansi4Bit::new_non_bright(Ansi3Bit::Yellow),
    Ansi4Bit::new_non_bright(Ansi3Bit::Blue),
    Ansi4Bit::new_non_bright(Ansi3Bit::Magenta),
    Ansi4Bit::new_non_bright(Ansi3Bit::Cyan),
    Ansi4Bit::new_non_bright(Ansi3Bit::White),
];

pub(super) const CUBE: [Cube; 216] = [
    Cube::new(0, 0, 0),
    Cube::new(0, 0, 1),
    Cube::new(0, 0, 2),
    Cube::new(0, 0, 3),
    Cube::new(0, 0, 4),
    Cube::new(0, 0, 5),
    Cube::new(0, 1, 0),
    Cube::new(0, 1, 1),
    Cube::new(0, 1, 2),
    Cube::new(0, 1, 3),
    Cube::new(0, 1, 4),
    Cube::new(0, 1, 5),
    Cube::new(0, 2, 0),
    Cube::new(0, 2, 1),
    Cube::new(0, 2, 2),
    Cube::new(0, 2, 3),
    Cube::new(0, 2, 4),
    Cube::new(0, 2, 5),
    Cube::new(0, 3, 0),
    Cube::new(0, 3, 1),
    Cube::new(0, 3, 2),
    Cube::new(0, 3, 3),
    Cube::new(0, 3, 4),
    Cube::new(0, 3, 5),
    Cube::new(0, 4, 0),
    Cube::new(0, 4, 1),
    Cube::new(0, 4, 2),
    Cube::new(0, 4, 3),
    Cube::new(0, 4, 4),
    Cube::new(0, 4, 5),
    Cube::new(0, 5, 0),
    Cube::new(0, 5, 1),
    Cube::new(0, 5, 2),
    Cube::new(0, 5, 3),
    Cube::new(0, 5, 4),
    Cube::new(0, 5, 5),
    Cube::new(1, 0, 0),
    Cube::new(1, 0, 1),
    Cube::new(1, 0, 2),
    Cube::new(1, 0, 3),
    Cube::new(1, 0, 4),
    Cube::new(1, 0, 5),
    Cube::new(1, 1, 0),
    Cube::new(1, 1, 1),
    Cube::new(1, 1, 2),
    Cube::new(1, 1, 3),
    Cube::new(1, 1, 4),
    Cube::new(1, 1, 5),
    Cube::new(1, 2, 0),
    Cube::new(1, 2, 1),
    Cube::new(1, 2, 2),
    Cube::new(1, 2, 3),
    Cube::new(1, 2, 4),
    Cube::new(1, 2, 5),
    Cube::new(1, 3, 0),
    Cube::new(1, 3, 1),
    Cube::new(1, 3, 2),
    Cube::new(1, 3, 3),
    Cube::new(1, 3, 4),
    Cube::new(1, 3, 5),
    Cube::new(1, 4, 0),
    Cube::new(1, 4, 1),
    Cube::new(1, 4, 2),
    Cube::new(1, 4, 3),
    Cube::new(1, 4, 4),
    Cube::new(1, 4, 5),
    Cube::new(1, 5, 0),
    Cube::new(1, 5, 1),
    Cube::new(1, 5, 2),
    Cube::new(1, 5, 3),
    Cube::new(1, 5, 4),
    Cube::new(1, 5, 5),
    Cube::new(2, 0, 0),
    Cube::new(2, 0, 1),
    Cube::new(2, 0, 2),
    Cube::new(2, 0, 3),
    Cube::new(2, 0, 4),
    Cube::new(2, 0, 5),
    Cube::new(2, 1, 0),
    Cube::new(2, 1, 1),
    Cube::new(2, 1, 2),
    Cube::new(2, 1, 3),
    Cube::new(2, 1, 4),
    Cube::new(2, 1, 5),
    Cube::new(2, 2, 0),
    Cube::new(2, 2, 1),
    Cube::new(2, 2, 2),
    Cube::new(2, 2, 3),
    Cube::new(2, 2, 4),
    Cube::new(2, 2, 5),
    Cube::new(2, 3, 0),
    Cube::new(2, 3, 1),
    Cube::new(2, 3, 2),
    Cube::new(2, 3, 3),
    Cube::new(2, 3, 4),
    Cube::new(2, 3, 5),
    Cube::new(2, 4, 0),
    Cube::new(2, 4, 1),
    Cube::new(2, 4, 2),
    Cube::new(2, 4, 3),
    Cube::new(2, 4, 4),
    Cube::new(2, 4, 5),
    Cube::new(2, 5, 0),
    Cube::new(2, 5, 1),
    Cube::new(2, 5, 2),
    Cube::new(2, 5, 3),
    Cube::new(2, 5, 4),
    Cube::new(2, 5, 5),
    Cube::new(3, 0, 0),
    Cube::new(3, 0, 1),
    Cube::new(3, 0, 2),
    Cube::new(3, 0, 3),
    Cube::new(3, 0, 4),
    Cube::new(3, 0, 5),
    Cube::new(3, 1, 0),
    Cube::new(3, 1, 1),
    Cube::new(3, 1, 2),
    Cube::new(3, 1, 3),
    Cube::new(3, 1, 4),
    Cube::new(3, 1, 5),
    Cube::new(3, 2, 0),
    Cube::new(3, 2, 1),
    Cube::new(3, 2, 2),
    Cube::new(3, 2, 3),
    Cube::new(3, 2, 4),
    Cube::new(3, 2, 5),
    Cube::new(3, 3, 0),
    Cube::new(3, 3, 1),
    Cube::new(3, 3, 2),
    Cube::new(3, 3, 3),
    Cube::new(3, 3, 4),
    Cube::new(3, 3, 5),
    Cube::new(3, 4, 0),
    Cube::new(3, 4, 1),
    Cube::new(3, 4, 2),
    Cube::new(3, 4, 3),
    Cube::new(3, 4, 4),
    Cube::new(3, 4, 5),
    Cube::new(3, 5, 0),
    Cube::new(3, 5, 1),
    Cube::new(3, 5, 2),
    Cube::new(3, 5, 3),
    Cube::new(3, 5, 4),
    Cube::new(3, 5, 5),
    Cube::new(4, 0, 0),
    Cube::new(4, 0, 1),
    Cube::new(4, 0, 2),
    Cube::new(4, 0, 3),
    Cube::new(4, 0, 4),
    Cube::new(4, 0, 5),
    Cube::new(4, 1, 0),
    Cube::new(4, 1, 1),
    Cube::new(4, 1, 2),
    Cube::new(4, 1, 3),
    Cube::new(4, 1, 4),
    Cube::new(4, 1, 5),
    Cube::new(4, 2, 0),
    Cube::new(4, 2, 1),
    Cube::new(4, 2, 2),
    Cube::new(4, 2, 3),
    Cube::new(4, 2, 4),
    Cube::new(4, 2, 5),
    Cube::new(4, 3, 0),
    Cube::new(4, 3, 1),
    Cube::new(4, 3, 2),
    Cube::new(4, 3, 3),
    Cube::new(4, 3, 4),
    Cube::new(4, 3, 5),
    Cube::new(4, 4, 0),
    Cube::new(4, 4, 1),
    Cube::new(4, 4, 2),
    Cube::new(4, 4, 3),
    Cube::new(4, 4, 4),
    Cube::new(4, 4, 5),
    Cube::new(4, 5, 0),
    Cube::new(4, 5, 1),
    Cube::new(4, 5, 2),
    Cube::new(4, 5, 3),
    Cube::new(4, 5, 4),
    Cube::new(4, 5, 5),
    Cube::new(5, 0, 0),
    Cube::new(5, 0, 1),
    Cube::new(5, 0, 2),
    Cube::new(5, 0, 3),
    Cube::new(5, 0, 4),
    Cube::new(5, 0, 5),
    Cube::new(5, 1, 0),
    Cube::new(5, 1, 1),
    Cube::new(5, 1, 2),
    Cube::new(5, 1, 3),
    Cube::new(5, 1, 4),
    Cube::new(5, 1, 5),
    Cube::new(5, 2, 0),
    Cube::new(5, 2, 1),
    Cube::new(5, 2, 2),
    Cube::new(5, 2, 3),
    Cube::new(5, 2, 4),
    Cube::new(5, 2, 5),
    Cube::new(5, 3, 0),
    Cube::new(5, 3, 1),
    Cube::new(5, 3, 2),
    Cube::new(5, 3, 3),
    Cube::new(5, 3, 4),
    Cube::new(5, 3, 5),
    Cube::new(5, 4, 0),
    Cube::new(5, 4, 1),
    Cube::new(5, 4, 2),
    Cube::new(5, 4, 3),
    Cube::new(5, 4, 4),
    Cube::new(5, 4, 5),
    Cube::new(5, 5, 0),
    Cube::new(5, 5, 1),
    Cube::new(5, 5, 2),
    Cube::new(5, 5, 3),
    Cube::new(5, 5, 4),
    Cube::new(5, 5, 5),
];

pub(super) const GRAYSCALE: [Grayscale; 24] = [
    Grayscale::new(1),
    Grayscale::new(2),
    Grayscale::new(3),
    Grayscale::new(4),
    Grayscale::new(5),
    Grayscale::new(6),
    Grayscale::new(7),
    Grayscale::new(8),
    Grayscale::new(9),
    Grayscale::new(10),
    Grayscale::new(11),
    Grayscale::new(12),
    Grayscale::new(13),
    Grayscale::new(14),
    Grayscale::new(15),
    Grayscale::new(16),
    Grayscale::new(17),
    Grayscale::new(18),
    Grayscale::new(19),
    Grayscale::new(20),
    Grayscale::new(21),
    Grayscale::new(22),
    Grayscale::new(23),
    Grayscale::new(24),
];

pub(super) const ANSI_8_BIT: [Ansi8Bit; 256] = [
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Black)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Red)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Green)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Yellow)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Blue)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Magenta)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::Cyan)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_bright(Ansi3Bit::White)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Black)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Red)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Green)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Yellow)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Blue)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Magenta)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::Cyan)),
    Ansi8Bit::Ansi4Bit(Ansi4Bit::new_non_bright(Ansi3Bit::White)),
    Ansi8Bit::Cube(Cube::new(0, 0, 0)),
    Ansi8Bit::Cube(Cube::new(0, 0, 1)),
    Ansi8Bit::Cube(Cube::new(0, 0, 2)),
    Ansi8Bit::Cube(Cube::new(0, 0, 3)),
    Ansi8Bit::Cube(Cube::new(0, 0, 4)),
    Ansi8Bit::Cube(Cube::new(0, 0, 5)),
    Ansi8Bit::Cube(Cube::new(0, 1, 0)),
    Ansi8Bit::Cube(Cube::new(0, 1, 1)),
    Ansi8Bit::Cube(Cube::new(0, 1, 2)),
    Ansi8Bit::Cube(Cube::new(0, 1, 3)),
    Ansi8Bit::Cube(Cube::new(0, 1, 4)),
    Ansi8Bit::Cube(Cube::new(0, 1, 5)),
    Ansi8Bit::Cube(Cube::new(0, 2, 0)),
    Ansi8Bit::Cube(Cube::new(0, 2, 1)),
    Ansi8Bit::Cube(Cube::new(0, 2, 2)),
    Ansi8Bit::Cube(Cube::new(0, 2, 3)),
    Ansi8Bit::Cube(Cube::new(0, 2, 4)),
    Ansi8Bit::Cube(Cube::new(0, 2, 5)),
    Ansi8Bit::Cube(Cube::new(0, 3, 0)),
    Ansi8Bit::Cube(Cube::new(0, 3, 1)),
    Ansi8Bit::Cube(Cube::new(0, 3, 2)),
    Ansi8Bit::Cube(Cube::new(0, 3, 3)),
    Ansi8Bit::Cube(Cube::new(0, 3, 4)),
    Ansi8Bit::Cube(Cube::new(0, 3, 5)),
    Ansi8Bit::Cube(Cube::new(0, 4, 0)),
    Ansi8Bit::Cube(Cube::new(0, 4, 1)),
    Ansi8Bit::Cube(Cube::new(0, 4, 2)),
    Ansi8Bit::Cube(Cube::new(0, 4, 3)),
    Ansi8Bit::Cube(Cube::new(0, 4, 4)),
    Ansi8Bit::Cube(Cube::new(0, 4, 5)),
    Ansi8Bit::Cube(Cube::new(0, 5, 0)),
    Ansi8Bit::Cube(Cube::new(0, 5, 1)),
    Ansi8Bit::Cube(Cube::new(0, 5, 2)),
    Ansi8Bit::Cube(Cube::new(0, 5, 3)),
    Ansi8Bit::Cube(Cube::new(0, 5, 4)),
    Ansi8Bit::Cube(Cube::new(0, 5, 5)),
    Ansi8Bit::Cube(Cube::new(1, 0, 0)),
    Ansi8Bit::Cube(Cube::new(1, 0, 1)),
    Ansi8Bit::Cube(Cube::new(1, 0, 2)),
    Ansi8Bit::Cube(Cube::new(1, 0, 3)),
    Ansi8Bit::Cube(Cube::new(1, 0, 4)),
    Ansi8Bit::Cube(Cube::new(1, 0, 5)),
    Ansi8Bit::Cube(Cube::new(1, 1, 0)),
    Ansi8Bit::Cube(Cube::new(1, 1, 1)),
    Ansi8Bit::Cube(Cube::new(1, 1, 2)),
    Ansi8Bit::Cube(Cube::new(1, 1, 3)),
    Ansi8Bit::Cube(Cube::new(1, 1, 4)),
    Ansi8Bit::Cube(Cube::new(1, 1, 5)),
    Ansi8Bit::Cube(Cube::new(1, 2, 0)),
    Ansi8Bit::Cube(Cube::new(1, 2, 1)),
    Ansi8Bit::Cube(Cube::new(1, 2, 2)),
    Ansi8Bit::Cube(Cube::new(1, 2, 3)),
    Ansi8Bit::Cube(Cube::new(1, 2, 4)),
    Ansi8Bit::Cube(Cube::new(1, 2, 5)),
    Ansi8Bit::Cube(Cube::new(1, 3, 0)),
    Ansi8Bit::Cube(Cube::new(1, 3, 1)),
    Ansi8Bit::Cube(Cube::new(1, 3, 2)),
    Ansi8Bit::Cube(Cube::new(1, 3, 3)),
    Ansi8Bit::Cube(Cube::new(1, 3, 4)),
    Ansi8Bit::Cube(Cube::new(1, 3, 5)),
    Ansi8Bit::Cube(Cube::new(1, 4, 0)),
    Ansi8Bit::Cube(Cube::new(1, 4, 1)),
    Ansi8Bit::Cube(Cube::new(1, 4, 2)),
    Ansi8Bit::Cube(Cube::new(1, 4, 3)),
    Ansi8Bit::Cube(Cube::new(1, 4, 4)),
    Ansi8Bit::Cube(Cube::new(1, 4, 5)),
    Ansi8Bit::Cube(Cube::new(1, 5, 0)),
    Ansi8Bit::Cube(Cube::new(1, 5, 1)),
    Ansi8Bit::Cube(Cube::new(1, 5, 2)),
    Ansi8Bit::Cube(Cube::new(1, 5, 3)),
    Ansi8Bit::Cube(Cube::new(1, 5, 4)),
    Ansi8Bit::Cube(Cube::new(1, 5, 5)),
    Ansi8Bit::Cube(Cube::new(2, 0, 0)),
    Ansi8Bit::Cube(Cube::new(2, 0, 1)),
    Ansi8Bit::Cube(Cube::new(2, 0, 2)),
    Ansi8Bit::Cube(Cube::new(2, 0, 3)),
    Ansi8Bit::Cube(Cube::new(2, 0, 4)),
    Ansi8Bit::Cube(Cube::new(2, 0, 5)),
    Ansi8Bit::Cube(Cube::new(2, 1, 0)),
    Ansi8Bit::Cube(Cube::new(2, 1, 1)),
    Ansi8Bit::Cube(Cube::new(2, 1, 2)),
    Ansi8Bit::Cube(Cube::new(2, 1, 3)),
    Ansi8Bit::Cube(Cube::new(2, 1, 4)),
    Ansi8Bit::Cube(Cube::new(2, 1, 5)),
    Ansi8Bit::Cube(Cube::new(2, 2, 0)),
    Ansi8Bit::Cube(Cube::new(2, 2, 1)),
    Ansi8Bit::Cube(Cube::new(2, 2, 2)),
    Ansi8Bit::Cube(Cube::new(2, 2, 3)),
    Ansi8Bit::Cube(Cube::new(2, 2, 4)),
    Ansi8Bit::Cube(Cube::new(2, 2, 5)),
    Ansi8Bit::Cube(Cube::new(2, 3, 0)),
    Ansi8Bit::Cube(Cube::new(2, 3, 1)),
    Ansi8Bit::Cube(Cube::new(2, 3, 2)),
    Ansi8Bit::Cube(Cube::new(2, 3, 3)),
    Ansi8Bit::Cube(Cube::new(2, 3, 4)),
    Ansi8Bit::Cube(Cube::new(2, 3, 5)),
    Ansi8Bit::Cube(Cube::new(2, 4, 0)),
    Ansi8Bit::Cube(Cube::new(2, 4, 1)),
    Ansi8Bit::Cube(Cube::new(2, 4, 2)),
    Ansi8Bit::Cube(Cube::new(2, 4, 3)),
    Ansi8Bit::Cube(Cube::new(2, 4, 4)),
    Ansi8Bit::Cube(Cube::new(2, 4, 5)),
    Ansi8Bit::Cube(Cube::new(2, 5, 0)),
    Ansi8Bit::Cube(Cube::new(2, 5, 1)),
    Ansi8Bit::Cube(Cube::new(2, 5, 2)),
    Ansi8Bit::Cube(Cube::new(2, 5, 3)),
    Ansi8Bit::Cube(Cube::new(2, 5, 4)),
    Ansi8Bit::Cube(Cube::new(2, 5, 5)),
    Ansi8Bit::Cube(Cube::new(3, 0, 0)),
    Ansi8Bit::Cube(Cube::new(3, 0, 1)),
    Ansi8Bit::Cube(Cube::new(3, 0, 2)),
    Ansi8Bit::Cube(Cube::new(3, 0, 3)),
    Ansi8Bit::Cube(Cube::new(3, 0, 4)),
    Ansi8Bit::Cube(Cube::new(3, 0, 5)),
    Ansi8Bit::Cube(Cube::new(3, 1, 0)),
    Ansi8Bit::Cube(Cube::new(3, 1, 1)),
    Ansi8Bit::Cube(Cube::new(3, 1, 2)),
    Ansi8Bit::Cube(Cube::new(3, 1, 3)),
    Ansi8Bit::Cube(Cube::new(3, 1, 4)),
    Ansi8Bit::Cube(Cube::new(3, 1, 5)),
    Ansi8Bit::Cube(Cube::new(3, 2, 0)),
    Ansi8Bit::Cube(Cube::new(3, 2, 1)),
    Ansi8Bit::Cube(Cube::new(3, 2, 2)),
    Ansi8Bit::Cube(Cube::new(3, 2, 3)),
    Ansi8Bit::Cube(Cube::new(3, 2, 4)),
    Ansi8Bit::Cube(Cube::new(3, 2, 5)),
    Ansi8Bit::Cube(Cube::new(3, 3, 0)),
    Ansi8Bit::Cube(Cube::new(3, 3, 1)),
    Ansi8Bit::Cube(Cube::new(3, 3, 2)),
    Ansi8Bit::Cube(Cube::new(3, 3, 3)),
    Ansi8Bit::Cube(Cube::new(3, 3, 4)),
    Ansi8Bit::Cube(Cube::new(3, 3, 5)),
    Ansi8Bit::Cube(Cube::new(3, 4, 0)),
    Ansi8Bit::Cube(Cube::new(3, 4, 1)),
    Ansi8Bit::Cube(Cube::new(3, 4, 2)),
    Ansi8Bit::Cube(Cube::new(3, 4, 3)),
    Ansi8Bit::Cube(Cube::new(3, 4, 4)),
    Ansi8Bit::Cube(Cube::new(3, 4, 5)),
    Ansi8Bit::Cube(Cube::new(3, 5, 0)),
    Ansi8Bit::Cube(Cube::new(3, 5, 1)),
    Ansi8Bit::Cube(Cube::new(3, 5, 2)),
    Ansi8Bit::Cube(Cube::new(3, 5, 3)),
    Ansi8Bit::Cube(Cube::new(3, 5, 4)),
    Ansi8Bit::Cube(Cube::new(3, 5, 5)),
    Ansi8Bit::Cube(Cube::new(4, 0, 0)),
    Ansi8Bit::Cube(Cube::new(4, 0, 1)),
    Ansi8Bit::Cube(Cube::new(4, 0, 2)),
    Ansi8Bit::Cube(Cube::new(4, 0, 3)),
    Ansi8Bit::Cube(Cube::new(4, 0, 4)),
    Ansi8Bit::Cube(Cube::new(4, 0, 5)),
    Ansi8Bit::Cube(Cube::new(4, 1, 0)),
    Ansi8Bit::Cube(Cube::new(4, 1, 1)),
    Ansi8Bit::Cube(Cube::new(4, 1, 2)),
    Ansi8Bit::Cube(Cube::new(4, 1, 3)),
    Ansi8Bit::Cube(Cube::new(4, 1, 4)),
    Ansi8Bit::Cube(Cube::new(4, 1, 5)),
    Ansi8Bit::Cube(Cube::new(4, 2, 0)),
    Ansi8Bit::Cube(Cube::new(4, 2, 1)),
    Ansi8Bit::Cube(Cube::new(4, 2, 2)),
    Ansi8Bit::Cube(Cube::new(4, 2, 3)),
    Ansi8Bit::Cube(Cube::new(4, 2, 4)),
    Ansi8Bit::Cube(Cube::new(4, 2, 5)),
    Ansi8Bit::Cube(Cube::new(4, 3, 0)),
    Ansi8Bit::Cube(Cube::new(4, 3, 1)),
    Ansi8Bit::Cube(Cube::new(4, 3, 2)),
    Ansi8Bit::Cube(Cube::new(4, 3, 3)),
    Ansi8Bit::Cube(Cube::new(4, 3, 4)),
    Ansi8Bit::Cube(Cube::new(4, 3, 5)),
    Ansi8Bit::Cube(Cube::new(4, 4, 0)),
    Ansi8Bit::Cube(Cube::new(4, 4, 1)),
    Ansi8Bit::Cube(Cube::new(4, 4, 2)),
    Ansi8Bit::Cube(Cube::new(4, 4, 3)),
    Ansi8Bit::Cube(Cube::new(4, 4, 4)),
    Ansi8Bit::Cube(Cube::new(4, 4, 5)),
    Ansi8Bit::Cube(Cube::new(4, 5, 0)),
    Ansi8Bit::Cube(Cube::new(4, 5, 1)),
    Ansi8Bit::Cube(Cube::new(4, 5, 2)),
    Ansi8Bit::Cube(Cube::new(4, 5, 3)),
    Ansi8Bit::Cube(Cube::new(4, 5, 4)),
    Ansi8Bit::Cube(Cube::new(4, 5, 5)),
    Ansi8Bit::Cube(Cube::new(5, 0, 0)),
    Ansi8Bit::Cube(Cube::new(5, 0, 1)),
    Ansi8Bit::Cube(Cube::new(5, 0, 2)),
    Ansi8Bit::Cube(Cube::new(5, 0, 3)),
    Ansi8Bit::Cube(Cube::new(5, 0, 4)),
    Ansi8Bit::Cube(Cube::new(5, 0, 5)),
    Ansi8Bit::Cube(Cube::new(5, 1, 0)),
    Ansi8Bit::Cube(Cube::new(5, 1, 1)),
    Ansi8Bit::Cube(Cube::new(5, 1, 2)),
    Ansi8Bit::Cube(Cube::new(5, 1, 3)),
    Ansi8Bit::Cube(Cube::new(5, 1, 4)),
    Ansi8Bit::Cube(Cube::new(5, 1, 5)),
    Ansi8Bit::Cube(Cube::new(5, 2, 0)),
    Ansi8Bit::Cube(Cube::new(5, 2, 1)),
    Ansi8Bit::Cube(Cube::new(5, 2, 2)),
    Ansi8Bit::Cube(Cube::new(5, 2, 3)),
    Ansi8Bit::Cube(Cube::new(5, 2, 4)),
    Ansi8Bit::Cube(Cube::new(5, 2, 5)),
    Ansi8Bit::Cube(Cube::new(5, 3, 0)),
    Ansi8Bit::Cube(Cube::new(5, 3, 1)),
    Ansi8Bit::Cube(Cube::new(5, 3, 2)),
    Ansi8Bit::Cube(Cube::new(5, 3, 3)),
    Ansi8Bit::Cube(Cube::new(5, 3, 4)),
    Ansi8Bit::Cube(Cube::new(5, 3, 5)),
    Ansi8Bit::Cube(Cube::new(5, 4, 0)),
    Ansi8Bit::Cube(Cube::new(5, 4, 1)),
    Ansi8Bit::Cube(Cube::new(5, 4, 2)),
    Ansi8Bit::Cube(Cube::new(5, 4, 3)),
    Ansi8Bit::Cube(Cube::new(5, 4, 4)),
    Ansi8Bit::Cube(Cube::new(5, 4, 5)),
    Ansi8Bit::Cube(Cube::new(5, 5, 0)),
    Ansi8Bit::Cube(Cube::new(5, 5, 1)),
    Ansi8Bit::Cube(Cube::new(5, 5, 2)),
    Ansi8Bit::Cube(Cube::new(5, 5, 3)),
    Ansi8Bit::Cube(Cube::new(5, 5, 4)),
    Ansi8Bit::Cube(Cube::new(5, 5, 5)),
    Ansi8Bit::Grayscale(Grayscale::new(1)),
    Ansi8Bit::Grayscale(Grayscale::new(2)),
    Ansi8Bit::Grayscale(Grayscale::new(3)),
    Ansi8Bit::Grayscale(Grayscale::new(4)),
    Ansi8Bit::Grayscale(Grayscale::new(5)),
    Ansi8Bit::Grayscale(Grayscale::new(6)),
    Ansi8Bit::Grayscale(Grayscale::new(7)),
    Ansi8Bit::Grayscale(Grayscale::new(8)),
    Ansi8Bit::Grayscale(Grayscale::new(9)),
    Ansi8Bit::Grayscale(Grayscale::new(10)),
    Ansi8Bit::Grayscale(Grayscale::new(11)),
    Ansi8Bit::Grayscale(Grayscale::new(12)),
    Ansi8Bit::Grayscale(Grayscale::new(13)),
    Ansi8Bit::Grayscale(Grayscale::new(14)),
    Ansi8Bit::Grayscale(Grayscale::new(15)),
    Ansi8Bit::Grayscale(Grayscale::new(16)),
    Ansi8Bit::Grayscale(Grayscale::new(17)),
    Ansi8Bit::Grayscale(Grayscale::new(18)),
    Ansi8Bit::Grayscale(Grayscale::new(19)),
    Ansi8Bit::Grayscale(Grayscale::new(20)),
    Ansi8Bit::Grayscale(Grayscale::new(21)),
    Ansi8Bit::Grayscale(Grayscale::new(22)),
    Ansi8Bit::Grayscale(Grayscale::new(23)),
    Ansi8Bit::Grayscale(Grayscale::new(24)),
];
